### ISSUE TITLE
扫描二维码超时... 错误信息：'data'

### ISSUE THREAD

**Issue by ylighgh** [TechXueXi/TechXueXi#256]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

Docker运行

### 软件/源码版本

techxuexi-amd64:latest

### 系统版本，包含位数

docker运行

### 浏览器、驱动版本

docker运行

### python版本

python3.7

### docker tag版本

techxuexi-amd64:latest

### 推送方式

6 网页推送

### 详细描述

docker 网页运行方式，扫码登陆失败

错误信息：

下午 1:02:04 | 扫描二维码超时... 错误信息：'data'

**Comment by cityTS** [comment]
请问有解决方案了吗

**Comment by ylighgh** [comment]
无，感觉这个项目黄了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: cityTS ***@***.***&gt;
发送时间: 2023年9月14日 12:37
收件人: TechXueXi/TechXueXi ***@***.***&gt;
抄送: ylighgh ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [TechXueXi/TechXueXi] 扫描二维码超时... 错误信息：'data' (Issue #256)

**Comment by huaji23** [comment]
请问有解决方案了吗

**Comment by atao-z** [comment]
感觉是api时间有问题,时区差个八个小时,但是不知道怎么处理

**Comment by GyyEcho** [comment]
有解决吗？感觉凉了

**Comment by hahahao62** [comment]
您好，您的邮件我已经收到。

**Comment by AmanITal** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fdq236** [comment]
您好，我已收到您发的邮件！待我看后回复！谢谢啦！
                                                                      pcq泉

**Comment by zhilinfan** [comment]
对，感觉是时间的问题

**Comment by licai28** [comment]
need fix

**Comment by huaji23** [comment]
还是不行

**Comment by Coder-DanielHan** [comment]
同样遇到这个问题了

**Comment by liangyuanshao** [comment]
你们是用国内的服务器吗？

**Comment by YangOu3500** [comment]
同样遇到这个问题  时间差距很大，扫二维码就失效

**Comment by zomgit** [comment]
如上方大佬们所说  搜索引擎“**docker 时区**”即可

**Comment by wattic** [comment]
已经更新了时区，时间和本地一致，并确认是CST。
这个问题依然存在，各种推送方式都会触发这个问题。

直接网页扫二维码是可以登录的。
在两台机器上（arm64v8/amd64)均复现了问题

**Comment by wattic** [comment]
如果服务器时间一致，则是接口换了，需要更新相关接口代码

**Comment by XATUCSJY** [comment]
> 已经更新了时区，时间和本地一致，并确认是CST。 这个问题依然存在，各种推送方式都会触发这个问题。
> 
> 直接网页扫二维码是可以登录的。 在两台机器上（arm64v8/amd64)均复现了问题

请问解决了吗，我现在将服务器与容器的时区更新一致后，web控制台中二维码区域：timestamp依然为“GMT”

**Comment by wattic** [comment]
@XATUCSJY  已经解决，我个人的问题和时间无关，是获取的代码版本落后，需要更新score.py，get_links.py等几个文件。具体你搜一下issues。

**Comment by GyyEcho** [comment]
老哥可以教一下嘛？









Echo

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年1月26日 11:24 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [TechXueXi/TechXueXi] 扫描二维码超时... 错误信息：'data' (Issue #256) |

已经解决，我个人的问题和时间无关，是获取的代码版本落后，需要更新score.py，get_links.py等几个文件。具体你搜一下issues。

**Comment by jinjd** [comment]
> @XATUCSJY 已经解决，我个人的问题和时间无关，是获取的代码版本落后，需要更新score.py，get_links.py等几个文件。具体你搜一下issues。

已经更新到最新代码了，还是报“扫描二维码超时... 错误信息：'data'”，问题怎么解决？

**Comment by ZqyDaoDao** [comment]
fix 了吗

**Comment by fdq236** [comment]
您好，我已收到您发的邮件！待我看后回复！谢谢啦！
                                                                      pcq泉

**Comment by hahahao62** [comment]
您好，您的邮件我已经收到。

**Comment by AmanITal** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wxjdsj** [comment]
我也遇到了这个问题，通过环境变量ENV TZ=Asia/Shanghai，仍然不好使

**Comment by XATUCSJY** [comment]
> 我也遇到了这个问题，通过环境变量ENV TZ=Asia/Shanghai，仍然不好使

#232，使用这个可以，测试ubuntu-wsl2-docker、windows-docker均可使用，windows下需要修改挂载路径。

**Comment by Goldenbeef** [comment]
不好用的可以借鉴一下我的
但是有个问题，目前扫码登陆之后有效期只有12小时，不知道这个问题怎么解决
```
services:
  techxuexi:
      image: techxuexi/techxuexi-amd64:dev89
      container_name: techxuexi-web
      restart: always
      shm_size: 2gb
      volumes:
            - ./xuexi:/xuexi/user
      ports:
          - 9980:80
      environment:
          - Pushmode=6
          - ZhuanXiang=True
          - Single=True
          - CRONTIME=48 10,18 * * *
          - Scheme=https://techxuexi.js.org/jump/techxuexi-20211023.html?
          - TZ=Asia/Shanghai
          - Sourcepath=https://github.com/TechXueXi/TechXueXi.git
```
